output: main.tex
	pdflatex main
	biber main
	pdflatex main
	pdflatex main
	rm -f *.aux *.bbl *.bcf *.blg *.log *.out *.xml *.toc *.lof *.lot
clean:
	rm -f *.aux *.bbl *.bcf *.blg *.log *.out *.xml *.toc *.lof *.lot
